spring.application.name=order-service
server.port=8083

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27020/order_db

# Feign — points to product-service and cart-service
product-service.url=http://localhost:8082
cart-service.url=http://localhost:8084

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
