spring.application.name=auth-service
server.port=8081

# MongoDB
spring.data.mongodb.uri=mongodb+srv://amudhana17_db_user:uStJxoCGc1JlvPVO@cluster0.zdkgd1u.mongodb.net/auth_db?retryWrites=true&w=majority&appName=Cluster0

# JWT
jwt.secret=Hj9Zsp8LxBKQn42eu+rOxrUg0qcBNm+K2z8LexKiD+k=
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
