spring.application.name=product-service
server.port=8082

# MongoDB
spring.data.mongodb.uri=mongodb+srv://amudhana17_db_user:uStJxoCGc1JlvPVO@cluster0.zdkgd1u.mongodb.net/product_db?retryWrites=true&w=majority&appName=Cluster0

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
