spring.application.name=cart-service
server.port=8084

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27019/cart_db

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
